export const itemsList = [
  {
    id: `grid-item${1}`,
    itemClass: "about-item1",
    doorClass: "bg-door1",
    dateClass: "date1",
    roleClass: "role1",
    date: "15/05/2000",
    role: "Frontend",
  },
  {
    id: `grid-item${2}`,
    itemClass: ".about-item2",
    doorClass: "bg-door2",
    dateClass: "date2",
    roleClass: "role2",
    date: "15/05/2000",
    role: "Frontend",
  },
  {
    id: `grid-item${3}`,
    itemClass: "about-item3",
    doorClass: "bg-door3",
    dateClass: "date3",
    roleClass: "role3",
    date: "15/05/2000",
    role: "Frontend",
  },
  {
    id: `grid-item${4}`,
    itemClass: "about-item4",
    doorClass: "bg-door4",
    dateClass: "date4",
    roleClass: "role4",
    date: "15/05/2000",
    role: "Frontend",
  },
  {
    id: `grid-item${5}`,
    itemClass: "about-item5",
    doorClass: "bg-door5",
    dateClass: "date5",
    roleClass: "role5",
    date: "15/05/2000",
    role: "Frontend",
  },
  {
    id: `grid-item${6}`,
    itemClass: "about-item",
    doorClass: "bg-door6",
    dateClass: "date6",
    roleClass: "role6",
    date: "15/05/2000",
    role: "Frontend",
  },
];
